### PR TITLE
Initialized Node project

### PR DESCRIPTION
**Pull request by Emilius123**
Hey, my boooooooooooooois. This is now a nice NodeJS Project initialized using NPM.

What do you think?

### CODE REVIEW

**Review by MoaufmKlo — CHANGES_REQUESTED** [review]
The description and the last keyword have weird characters in them.
Use authors instead of author.

**Comment by Emilius123** [comment]
Fixed the eye Cancer parts. Could you please set the changes to made now, please?

**Review by MoaufmKlo — CHANGES_REQUESTED** [review]
Correct username: MoamAufmklo to MoaufmKlo

**Comment by Emilius123** [comment]
Fixed.
Is that all for this pull request?

**Review by MoaufmKlo — CHANGES_REQUESTED** [review]
"constributors" is an invalid tag.

**Comment by Emilius123** [comment]
Which should I use then?

**Comment by MoaufmKlo** [comment]
contributors, it's a spelling mistake.

**Comment by Emilius123** [comment]
I suck at everything today. Fixed...

**Review by MoaufmKlo — CHANGES_REQUESTED** [review]
There's a ; at the end, it has to be a ,

**Comment by Emilius123** [comment]
At the end of what?

**Comment by MoaufmKlo** [comment]
Line 25.

**Comment by Emilius123** [comment]
What about now?

**Comment by Emilius123** [comment]
I'll use VS Code from now on, that will give me Errors Right away.

**Review by MoaufmKlo — APPROVED** [review]
Looks good.

**Comment by Emilius123** [comment]
Ancient, when you reviewed this and everything is OK, you can merge it.

**Review by MoaufmKlo — APPROVED** [review]

**Pull request merged**
